<?php
/** @var Amasty\Course\Block\Form $block */
?>

<form class="am">
    <div class="am">
        <input name="sku" type="text"/>
    </div>
    <div class="am">
        <input name="qty" type="number"/>
    </div>
    <div class="am">
        <?= $block->getChildHtml('amasty.course.additionalBlock') ?>
    </div>
    <button type="submit" title="Add to Card" class="action tocart primary">
        <span>Add to Card</span>
    </button>
</form>
