<?php
/** @var Amasty\Course\Block\Form $block */

$className = $block->hasCssClass() ? $block->getCssClass() : '';
?>

<form class="<?= $className ?>" action="<?= $block->getUrlAction() ?>" method="post">
    <div class="am">
        <label for="sku">
            <span>Product SKU</span>
        </label>
        <div>
            <input id="sku" name="sku" type="text" value=""/>
        </div>
    </div>
    <?php if ($block->showQty()): ?>
        <div class="am">
            <label for="qty">
                <span>Product Qty</span>
            </label>
            <div>
                <input id="qty" name="qty" type="number" min="0" value="<?= $block->getQty() ?>"/>
            </div>
        </div>
    <?php endif; ?>
    <div class="am">
        <?= $block->getChildHtml() ?>
    </div>
    <button type="submit" title="Add to Card" class="action tocart primary">
        <span>Add to Card</span>
    </button>
</form>
