<?php
/** @var Amasty\Course\Block\Form $block */
?>
<?php
$_className = $this->hasCssClass() ? $this->getCssClass() : '';
?>

<form class="<?= $_className ?>" action="<?= $block->getUrlAction() ?>" method="post">
    <div class="am">
        <label for="sku">
            <span>Product SKU</span>
        </label>
        <div class="am">
            <input id="sku" name="sku" type="text" value=""/>
        </div>
    </div>
    <?php if ($block->showQty()) { ?>
        <div class="am">
            <label for="qty">
                <span>Product Qty</span>
            </label>
            <div class="am">
                <input id="qty" name="qty" type="number" value="<?= $block->qty() ?>"/>
            </div>
        </div>
    <?php } ?>
    <div class="am">
        <?= $block->getChildHtml('amasty.course.additionalBlock') ?>
    </div>
    <button type="submit" title="Add to Card" class="action tocart primary">
        <span>Add to Card</span>
    </button>
</form>
